/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DashboardStats {
    out: bigint;
    incomplete: bigint;
    available: bigint;
    returned: bigint;
}
export interface ActivityLogEntry {
    action: Variant_created_loadoutSet_statusChanged_checkedOut_returned;
    trailerId: bigint;
    user: Principal;
    timestamp: Time;
    details: string;
}
export type Time = bigint;
export interface LoadoutItem {
    quantity: bigint;
    partTypeId: bigint;
}
export interface Trailer {
    id: bigint;
    status: TrailerStatus;
    code: string;
    name: string;
    description: string;
}
export interface PartType {
    id: bigint;
    name: string;
    unitLabel: string;
}
export interface UserProfile {
    name: string;
}
export interface ReturnItem {
    expectedCount: bigint;
    actualCount: bigint;
    discrepancy: Variant_ok_missing_extra;
    partTypeId: bigint;
}
export enum TrailerStatus {
    out = "out",
    incomplete = "incomplete",
    available = "available",
    returned = "returned"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_created_loadoutSet_statusChanged_checkedOut_returned {
    created = "created",
    loadoutSet = "loadoutSet",
    statusChanged = "statusChanged",
    checkedOut = "checkedOut",
    returned = "returned"
}
export enum Variant_ok_missing_extra {
    ok = "ok",
    missing = "missing",
    extra = "extra"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkoutTrailer(trailerId: bigint, photoHashes: Array<string>): Promise<void>;
    createPartType(name: string, unitLabel: string): Promise<bigint>;
    createTrailer(code: string, name: string, description: string): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getLoadout(trailerId: bigint): Promise<Array<LoadoutItem>>;
    getTrailer(id: bigint): Promise<Trailer>;
    getTrailerLog(trailerId: bigint): Promise<Array<ActivityLogEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listPartTypes(): Promise<Array<PartType>>;
    listTrailers(): Promise<Array<Trailer>>;
    returnTrailer(trailerId: bigint, actualItems: Array<ReturnItem>, photoHashes: Array<string>): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setLoadout(trailerId: bigint, items: Array<LoadoutItem>): Promise<void>;
    updateTrailer(id: bigint, name: string, description: string, status: TrailerStatus): Promise<void>;
}
import type { ActivityLogEntry as _ActivityLogEntry, ReturnItem as _ReturnItem, Time as _Time, Trailer as _Trailer, TrailerStatus as _TrailerStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkoutTrailer(arg0: bigint, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkoutTrailer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkoutTrailer(arg0, arg1);
            return result;
        }
    }
    async createPartType(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPartType(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPartType(arg0, arg1);
            return result;
        }
    }
    async createTrailer(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrailer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrailer(arg0, arg1, arg2);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getLoadout(arg0: bigint): Promise<Array<LoadoutItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoadout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoadout(arg0);
            return result;
        }
    }
    async getTrailer(arg0: bigint): Promise<Trailer> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrailer(arg0);
                return from_candid_Trailer_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrailer(arg0);
            return from_candid_Trailer_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrailerLog(arg0: bigint): Promise<Array<ActivityLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrailerLog(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrailerLog(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listPartTypes(): Promise<Array<PartType>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPartTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPartTypes();
            return result;
        }
    }
    async listTrailers(): Promise<Array<Trailer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrailers();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrailers();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async returnTrailer(arg0: bigint, arg1: Array<ReturnItem>, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.returnTrailer(arg0, to_candid_vec_n15(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.returnTrailer(arg0, to_candid_vec_n15(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setLoadout(arg0: bigint, arg1: Array<LoadoutItem>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLoadout(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLoadout(arg0, arg1);
            return result;
        }
    }
    async updateTrailer(arg0: bigint, arg1: string, arg2: string, arg3: TrailerStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrailer(arg0, arg1, arg2, to_candid_TrailerStatus_n19(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrailer(arg0, arg1, arg2, to_candid_TrailerStatus_n19(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_ActivityLogEntry_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLogEntry): ActivityLogEntry {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TrailerStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrailerStatus): TrailerStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Trailer_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trailer): Trailer {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: {
        created: null;
    } | {
        loadoutSet: null;
    } | {
        statusChanged: null;
    } | {
        checkedOut: null;
    } | {
        returned: null;
    };
    trailerId: bigint;
    user: Principal;
    timestamp: _Time;
    details: string;
}): {
    action: Variant_created_loadoutSet_statusChanged_checkedOut_returned;
    trailerId: bigint;
    user: Principal;
    timestamp: Time;
    details: string;
} {
    return {
        action: from_candid_variant_n13(_uploadFile, _downloadFile, value.action),
        trailerId: value.trailerId,
        user: value.user,
        timestamp: value.timestamp,
        details: value.details
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TrailerStatus;
    code: string;
    name: string;
    description: string;
}): {
    id: bigint;
    status: TrailerStatus;
    code: string;
    name: string;
    description: string;
} {
    return {
        id: value.id,
        status: from_candid_TrailerStatus_n8(_uploadFile, _downloadFile, value.status),
        code: value.code,
        name: value.name,
        description: value.description
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: null;
} | {
    loadoutSet: null;
} | {
    statusChanged: null;
} | {
    checkedOut: null;
} | {
    returned: null;
}): Variant_created_loadoutSet_statusChanged_checkedOut_returned {
    return "created" in value ? Variant_created_loadoutSet_statusChanged_checkedOut_returned.created : "loadoutSet" in value ? Variant_created_loadoutSet_statusChanged_checkedOut_returned.loadoutSet : "statusChanged" in value ? Variant_created_loadoutSet_statusChanged_checkedOut_returned.statusChanged : "checkedOut" in value ? Variant_created_loadoutSet_statusChanged_checkedOut_returned.checkedOut : "returned" in value ? Variant_created_loadoutSet_statusChanged_checkedOut_returned.returned : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    out: null;
} | {
    incomplete: null;
} | {
    available: null;
} | {
    returned: null;
}): TrailerStatus {
    return "out" in value ? TrailerStatus.out : "incomplete" in value ? TrailerStatus.incomplete : "available" in value ? TrailerStatus.available : "returned" in value ? TrailerStatus.returned : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityLogEntry>): Array<ActivityLogEntry> {
    return value.map((x)=>from_candid_ActivityLogEntry_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trailer>): Array<Trailer> {
    return value.map((x)=>from_candid_Trailer_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ReturnItem_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReturnItem): _ReturnItem {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_TrailerStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrailerStatus): _TrailerStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expectedCount: bigint;
    actualCount: bigint;
    discrepancy: Variant_ok_missing_extra;
    partTypeId: bigint;
}): {
    expectedCount: bigint;
    actualCount: bigint;
    discrepancy: {
        ok: null;
    } | {
        missing: null;
    } | {
        extra: null;
    };
    partTypeId: bigint;
} {
    return {
        expectedCount: value.expectedCount,
        actualCount: value.actualCount,
        discrepancy: to_candid_variant_n18(_uploadFile, _downloadFile, value.discrepancy),
        partTypeId: value.partTypeId
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_ok_missing_extra): {
    ok: null;
} | {
    missing: null;
} | {
    extra: null;
} {
    return value == Variant_ok_missing_extra.ok ? {
        ok: null
    } : value == Variant_ok_missing_extra.missing ? {
        missing: null
    } : value == Variant_ok_missing_extra.extra ? {
        extra: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrailerStatus): {
    out: null;
} | {
    incomplete: null;
} | {
    available: null;
} | {
    returned: null;
} {
    return value == TrailerStatus.out ? {
        out: null
    } : value == TrailerStatus.incomplete ? {
        incomplete: null
    } : value == TrailerStatus.available ? {
        available: null
    } : value == TrailerStatus.returned ? {
        returned: null
    } : value;
}
function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ReturnItem>): Array<_ReturnItem> {
    return value.map((x)=>to_candid_ReturnItem_n16(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
